- name: ruby dependencies
  yum: name={{item}}
       state=installed
  with_items:
    - gcc-c++
    - git
    - glibc-devel
    - glibc-headers
    - libyaml-devel
    - openssl-devel
    - readline
    - readline-devel
    - zlib
    - zlib-devel

- name: download ruby build
  git: repo=https://github.com/sstephenson/ruby-build.git
    dest=/opt/src/ruby-build
    update=no

- name: compile ruby build
  command: ./install.sh
      chdir=/opt/src/ruby-build
      creates=/usr/local/bin/ruby-build

- name: make ruby directory
  file: path=/opt/rubies
        owner=root
        group=root
        state=directory

- name: download chruby
  get_url: url=https://github.com/postmodern/chruby/archive/v{{chruby.version}}.tar.gz
        dest=/opt/src/chruby-{{chruby.version}}.tar.gz

- name: expand chruby
  command: tar -C /opt/src -xvzf /opt/src/chruby-{{chruby.version}}.tar.gz
    creates=/opt/src/chruby-{{chruby.version}}/Makefile

- name: compile chruby
  command: make install
        chdir=/opt/src/chruby-{{chruby.version}}
        creates=/usr/local/share/chruby/chruby.sh

- name: install chruby profile
  copy: src=chruby.sh
        dest=/etc/profile.d/chruby.sh
        mode=644

- name: compile ruby
  command: /usr/local/bin/ruby-build {{ruby.version}} /opt/rubies/{{ruby.version}}
        creates=/opt/rubies/{{ruby.version}}/bin/ruby

