---
- name: install log4j
  sudo: yes
  yum: name=log4j
       state=installed

- file: path={{item}} state=directory
  sudo: yes
  with_items:
    - /opt/src
    - /opt/local

- name: Check variable solr.version is set
  fail: msg="Please set 'solr.version' variable in the playbook"
  when: solr.version is not defined

- name: Download SOLR
  copy: src=solr-{{solr.version}}.zip
        dest=/opt/src/solr-{{solr.version}}.zip
        owner=tomcat
        group=tomcat
  sudo: yes

#  get_url: url=http://mirror.tcpdiag.net/apache/lucene/solr/{{solr.version}}/solr-{{solr.version}}.zip
#           dest=/opt/src/solr-{{solr.version}}.zip
#           sha256sum=aa0528975fa38b08de2000aae747b5f0a89c4232b2279280ad2f5d0ab58cbc82

- name: Setup directories
  file: path={{item}}
        state=directory
        owner=tomcat
        group=tomcat
  sudo: yes
  with_items:
    - /opt/solr
    - /opt/solr/bin
    - /opt/solr/lib

- name: Unpack SOLR
  command: unzip -d /opt/local /opt/src/solr-{{solr.version}}.zip
        creates=/opt/local/solr-{{solr.version}}/dist/solr-{{solr.version}}.war
  sudo: yes

- name: Copy solr.war into place
  command: cp /opt/local/solr-{{solr.version}}/dist/solr-{{solr.version}}.war /opt/solr/solr-{{solr.version}}.war
        creates=/opt/solr/solr-{{solr.version}}.war
  sudo: yes

- name: copy solr jar files
  command: cp /opt/local/solr-{{solr.version}}/{{item}} /opt/solr/lib
        creates=/opt/solr/lib/{{item | basename}}
  sudo: yes
  with_items:
    - dist/solr-analysis-extras-{{solr.version}}.jar
    - dist/solr-cell-{{solr.version}}.jar
    - dist/solr-clustering-{{solr.version}}.jar
    - dist/solr-core-{{solr.version}}.jar
    - dist/solr-dataimporthandler-{{solr.version}}.jar
    - dist/solr-dataimporthandler-extras-{{solr.version}}.jar
    - dist/solr-langid-{{solr.version}}.jar
    - dist/solr-map-reduce-{{solr.version}}.jar
    - dist/solr-morphlines-cell-{{solr.version}}.jar
    - dist/solr-morphlines-core-{{solr.version}}.jar
    - dist/solr-solrj-{{solr.version}}.jar
    - dist/solr-test-framework-{{solr.version}}.jar
    - dist/solr-uima-{{solr.version}}.jar
    - dist/solr-velocity-{{solr.version}}.jar
    - contrib/analysis-extras/lib/icu4j-53.1.jar
    - contrib/analysis-extras/lucene-libs/lucene-analyzers-icu-{{solr.version}}.jar

- command: cp /opt/local/solr-{{solr.version}}/example/{{item}} /usr/share/tomcat6/lib
    creates=/usr/share/tomcat6/lib/{{item | basename}}
  sudo: yes
  with_items:
    - lib/ext/jcl-over-slf4j-1.7.6.jar
    - lib/ext/jul-to-slf4j-1.7.6.jar
    - lib/ext/log4j-1.2.17.jar
    - lib/ext/slf4j-api-1.7.6.jar
    - lib/ext/slf4j-log4j12-1.7.6.jar
    - resources/log4j.properties

- lineinfile: line="common.loader=${catalina.base}/lib,${catalina.base}/lib/*.jar,${catalina.home}/lib,${catalina.home}/lib/*.jar,/opt/solr-4.3.0/lib/ext/*.jar,/opt/solr-4.3.0/lib/contrib/extraction/lib/*.jar"
        regexp="^common.loader"
        dest=/etc/tomcat6/catalina.properties
  sudo: yes

- name: Correct ownership
  sudo: yes
  file: owner=tomcat
        group=tomcat
        path=/opt/solr
        recurse=yes
        state=directory

#
# setup vecnet core
#

- name: Install solr configuration
  sudo: yes
  template: >
    src=solr.xml.j2
    dest=/opt/solr/solr.xml
    owner=tomcat
    group=tomcat

- name: Setup vecnet directory
  file: path=/opt/solr/vecnet/conf
        state=directory
        owner=tomcat
        group=tomcat
  sudo: yes

- name: Copy vecnet solr config
  copy: src={{item}}
        dest=/opt/solr/vecnet/conf/{{item}}
        owner=tomcat
        group=tomcat
        mode=644
  sudo: yes
  with_items:
    - protwords.txt
    - schema.xml
    - solrconfig.xml
    - stopwords_en.txt
    - synonyms.txt

- name: Copy solr.xml into tomcat
  sudo: yes
  template: >
    src=solr-production.j2
    dest=/etc/tomcat6/Catalina/localhost/solr.xml
    owner=tomcat
    group=tomcat
  notify: restart tomcat
