---
- yum: name={{item}} state=present
  sudo: yes
  with_items:
    - unzip

- name: create /opt/src
  file: path=/opt/src
        state=directory
  sudo: yes

- name: download fits
  get_url: url=http://dl.vecnet.org/i/fits-{{fits.version}}.zip
           dest=/opt/src/fits-{{fits.version}}.zip

- name: expand fits
  unarchive: src=/opt/src/fits-{{fits.version}}.zip
      dest=/opt/src
      copy=no
      owner=root
      group=root
      creates=/opt/src/fits-{{fits.version}}/fits.sh
  sudo: yes

- file: src=/opt/src/fits-{{fits.version}}
        dest=/opt/fits
        state=link
  sudo: yes

- file: path=/opt/fits/fits.sh
        state=file
        mode=0755
  sudo: yes

