- name: Install epel yum repository info
  hosts: all
  sudo: yes
  tasks:
    - name: copy epel rpm file
      copy: src=files/epel-release-6-8.noarch.rpm
            dest=/opt/src/epel-release-6-8.noarch.rpm
    - name: install epel rpm
      yum:  name=/opt/src/epel-release-6-8.noarch.rpm
            state=present

