---
- name: Base packages
  hosts: all
  include: fedora-epel.yml

- hosts: all
  include: common.yml

- name: Standalone
  hosts: all
  sudo: yes
  roles:
    - postgres
    - redis
    - fits
    - tomcat
    - solr
    - ruby
    - nginx
    #- { role: geerlingguy.solr, workspace: /opt/local, tomcat6_hostname: localhost, solr_cores: [ vecnet ], sudo: yes}
