---
- name: Install Postgres Server
  hosts: all
  sudo: yes
  tasks:
    - name: Install packages
      yum: name={{ item }}
           state=installed
      with_items:
       - python-psycopg2
       - postgresql-server
       - postgresql

    - name: Init postgresql
      command: service postgresql initdb
               creates=/var/lib/pgsql/data/postgresql.conf

    - name: Update pg_hba.conf
      sudo: yes
      copy: src=files/pg_hba.conf
            dest=/var/lib/pgsql/data/pg_hba.conf
            owner=postgres
            group=postgres
            mode=0640
      notify:
        - reload postgresql

    - name: Start postgresql
      service: name=postgresql
               enabled=yes
               state=started

    - name: Add vecnet database
      postgresql_db: name=vecnet_db

    - name: Add vecnet db user
      postgresql_user: db=vecnet_db name=vecnet encrypted=yes password=md586655461c3f6f1054157d24eeeeccbf7 priv=ALL

    - name: Make fedora database
      postgresql_db: name=fedora

    - name: Make fedora user
      postgresql_user: db=fedora name=fedora encrypted=yes password=md5c2bbdf29f656955b46e2f349414ba9d4 priv=ALL

  handlers:
    - name: restart postgresql
      sudo: yes
      service: name=postgresql state=restarted enabled=yes

    - name: reload postgresql
      sudo: yes
      service: name=postgresql state=reloaded enabled=yes

