---
- name: Install Postgres Server
  hosts: dbserver
  sudo: yes
  tasks:
    - name: Install packages
      yum: name={{ item }}
           state=installed
      with_items:
       - python-psycopg2
       - postgresql-server
       - postgresql

    - name: Init postgresql
      command: service postgresql initdb
               creates=/var/lib/pgsql/data/postgresql.conf

    - name: Start postgresql
      service: name=postgresql
               enabled=yes
               state=started

    - name: Ensure PostgreSQL is listening on all localhost
      lineinfile: dest=/var/lib/pgsql/data/postgresql.conf
        regexp='^#?listen_addresses\s*='
        line="listen_addresses = '127.0.0.1'"
        state=present
      notify: restart postgresql

    - lineinfile: dest=/var/lib/pgsql/data/pg_hba.conf
                  regexp='host\s+all\s+all\s+127.0.0.1/32\s+md5'
                  line='host all all 127.0.0.1/32 md5'
                  insertbefore=BOF
      notify: restart postgresql

  handlers:
    - name: restart postgresql
      service: name=postgresql state=restarted

#     - name: Add vecnet db user
#       postgresql_user: name=vecnet encrypted=yes password=md586655461c3f6f1054157d24eeeeccbf7
# 
#     - name: Add vecnet database
#       postgresql_db: name=vecnet_db owner=vecnet
# 
#     - name: vecnet DB permissions
#       postgresql_privs:
#         db=vecnet_db
#         privs=ALL
#         type=database
#         role=vecnet
# 
#     - name: Make fedora user
#       postgresql_user: name=fedora encrypted=yes password=md5c2bbdf29f656955b46e2f349414ba9d4
# 
#     - name: Make fedora database
#       postgresql_db: name=fedora owner=fedora
# 
#     - name: fedora DB permissions
#       postgresql_privs:
#         db=fedora
#         privs=ALL
#         type=database
#         role=fedora



